---
stages:
  - build
  - configuration

build-pnl-dependencies-job:
  stage: build
  tags: [pnl]
  script:
    - cpanm -L local -nq --installdeps .
    - mkdir -p             deploy
    - cp -av bin/          deploy/
    - cp -av lib/          deploy/
    - cp -av public/       deploy/
    - cp -av views/        deploy/
    - cp -av environments/ deploy/
    - cp -a  local/        deploy/
    - cp -v  config.yml    deploy/
  cache:
    key: pnl_deps
    paths:
      - local/
  artifacts:
    expose_as: pnl_app
    paths:
      - deploy/

merge-pnl-config-job:
  stage: configuration
  dependencies:
    - "build-pnl-dependencies-job"
  tags: [pnl]
  artifacts:
    paths:
      - deploy/
  script:
    - echo "script-section"
    - 'curl -s -H"JOB-TOKEN: $CI_JOB_TOKEN" http://fidogitlab.fritz.box/api/v4/projects/4/jobs/artifacts/main/download?job=build-pnl-artifacts-job | bsdtar -xvf - -C .'
    - cp -av pnlconfig/. deploy/
